### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by SvenAbels** [zivillian/ora2mqtt#19]
Since about 2 days I get an error 500 in the logs and the programm terminates:

```
Access token expired (Login Token has expired). Trying to refresh token...
System.Net.Http.HttpRequestException: Response status code does not indicate success: 500 (Internal Server Error).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at libgwmapi.GwmApiClient.GetResponseAsync[T](HttpResponseMessage response, CancellationToken cancellationToken) in /app/libgwmapi/GwmApiClient.cs:line 116
   at libgwmapi.GwmApiClient.PostH5Async[TIn,TOut](String url, TIn body, CancellationToken cancellationToken) in /app/libgwmapi/GwmApiClient.cs:line 92
   at ora2mqtt.RunCommand.RefreshTokenAsync(GwmApiClient client, Ora2MqttOptions options, CancellationToken cancellationToken) in /app/ora2mqtt/RunCommand.cs:line 102
   at ora2mqtt.RunCommand.Run(CancellationToken cancellationToken) in /app/ora2mqtt/RunCommand.cs:line 40
   at Program.<Main>$(String[] args) in /app/ora2mqtt/Program.cs:line 23
```

Does anyone have the same error?

**Comment by zivillian** [comment]
I had the same error a few weeks ago and the only way I found to fix this was to create new tokens by running configure again and logging in using the email and code.

**Comment by daemonenstall** [comment]
I also had this error and running configure again fixed it. Today it happened again, but now it's not working anymore. Any ideas?
`System.Net.Http.HttpRequestException: Response status code does not indicate success: 500 (Internal Server Error).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at libgwmapi.GwmApiClient.GetResponseAsync[T](HttpResponseMessage response, CancellationToken cancellationToken) in /home/runner/work/ora2mqtt/ora2mqtt/libgwmapi/GwmApiClient.cs:line 116
   at libgwmapi.GwmApiClient.PostH5Async[TIn,TOut](String url, TIn body, CancellationToken cancellationToken) in /home/runner/work/ora2mqtt/ora2mqtt/libgwmapi/GwmApiClient.cs:line 92
   at ora2mqtt.ConfigureCommand.LoginAsync(GwmApiClient client, Ora2MqttOptions options, CancellationToken cancellationToken) in /home/runner/work/ora2mqtt/ora2mqtt/ora2mqtt/ConfigureCommand.cs:line 110
   at ora2mqtt.ConfigureCommand.Run(CancellationToken cancellationToken) in /home/runner/work/ora2mqtt/ora2mqtt/ora2mqtt/ConfigureCommand.cs:line 41
   at Program.<Main>$(String[] args) in /home/runner/work/ora2mqtt/ora2mqtt/ora2mqtt/Program.cs:line 23
`

**Comment by cram-89** [comment]
@zivillian auch mit der neuen v0.0.3 bekomme ich bei der win64 Version weiterhin den 500 Fehler nach E-Mail- und Passwort-Eingabe

**Comment by holger1414** [comment]
The same error here.

Kontakt cram-89 ***@***.***>) kirjutas kuupäeval T, 6.
august 2024 kell 21:57:

**Comment by zivillian** [comment]
can you try [the binaries](https://github.com/zivillian/ora2mqtt/actions/runs/10273350325#artifacts) from #22?

**Comment by daemonenstall** [comment]
I have just tried the fresh binaries and error 500 is gone. Mille grazie :)

**Comment by gratefulUser1** [comment]
So do you get the SOC and range values again in MQTT? For me,I still have the issue, that even the My GWM app does not show these values ...

**Comment by holger1414** [comment]
Everything working very well.
Thank you!

**Comment by daemonenstall** [comment]
Everything is working.
