### ISSUE TITLE
Response status code does not indicate success

### ISSUE THREAD

**Issue by nicpear** [zivillian/ora2mqtt#21]
Hallo,
ich bekomme seit kurzem diesen Fehler:
`System.Net.Http.HttpRequestException: Response status code does not indicate success: 500 (Internal Server Error).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at libgwmapi.GwmApiClient.GetResponseAsync[T](HttpResponseMessage response, CancellationToken cancellationToken) in /home/runner/work/ora2mqtt/ora2mqtt/libgwmapi/GwmApiClient.cs:line 116
   at libgwmapi.GwmApiClient.PostH5Async[TIn,TOut](String url, TIn body, CancellationToken cancellationToken) in /home/runner/work/ora2mqtt/ora2mqtt/libgwmapi/GwmApiClient.cs:line 92
   at ora2mqtt.ConfigureCommand.LoginAsync(GwmApiClient client, Ora2MqttOptions options, CancellationToken cancellationToken) in /home/runner/work/ora2mqtt/ora2mqtt/ora2mqtt/ConfigureCommand.cs:line 110
   at ora2mqtt.ConfigureCommand.Run(CancellationToken cancellationToken) in /home/runner/work/ora2mqtt/ora2mqtt/ora2mqtt/ConfigureCommand.cs:line 41
   at Program.<Main>$(String[] args) in /home/runner/work/ora2mqtt/ora2mqtt/ora2mqtt/Program.cs:line 23`

Hast du eine Idee, was das sein könnte? Die App funktioniert weiterhin.

Viele Grüße

**Comment by daemonenstall** [comment]
Gleiches Problem hier. Vor einiger Zeit hatte ich den Fehler auch und konnte ihn mit einem erneuten
`ora2mqtt configure` beheben.

**Comment by gratefulUser1** [comment]
Ich hatte diesen Fehler ganz oft, ich habe das Programm deswegen in einer Endlosschleife immer wieder neugestartet, das war bis zum App-Update auch kein Problem.

**Comment by zivillian** [comment]
das sieht nach dem gleichen Fehler wie in #19 aus
