### ISSUE TITLE
The docker is going down constantly

### ISSUE THREAD

**Issue by Jens-Wymeersch** [zivillian/ora2mqtt#32]
Hello,

After a 3 month of running the container successfully. I am now having a lot of trouble.
Here you see the error message, not sure what to do 

`System.Net.Http.HttpRequestException: Response status code does not indicate success: 503 (Service Temporarily Unavailable).

   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()

   at libgwmapi.GwmApiClient.GetResponseAsync[T](HttpResponseMessage response, CancellationToken cancellationToken) in /app/libgwmapi/GwmApiClient.cs:line 117

   at libgwmapi.GwmApiClient.GetH5Async[T](String url, CancellationToken cancellationToken) in /app/libgwmapi/GwmApiClient.cs:line 99

   at ora2mqtt.RunCommand.RefreshTokenAsync(GwmApiClient client, Ora2MqttOptions options, CancellationToken cancellationToken) in /app/ora2mqtt/RunCommand.cs:line 89

   at ora2mqtt.RunCommand.Run(CancellationToken cancellationToken) in /app/ora2mqtt/RunCommand.cs:line 41

   at Program.<Main>$(String[] args) in /app/ora2mqtt/Program.cs:line 23`

**Comment by Jens-Wymeersch** [comment]
new authentication needed
